# BeatMatcher 配置文件

# 日志配置
logging:
  level: "INFO"
  file: "logs/beatmatcher.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} | {message}"
  rotation: "10 MB"
  retention: "7 days"

# BeatSaver API 配置
beatsaver:
  base_url: "https://api.beatsaver.com"
  search_endpoint: "/search/text"
  download_endpoint: "/download/key/{id}"
  request_delay: 1.0  # 请求间隔秒数
  max_retries: 3
  timeout: 30
  user_agent: "BeatMatcher/1.0"

# 匹配配置
matching:
  # 匹配权重
  artist_weight: 0.6
  title_weight: 0.4
  
  # 相似度阈值 (0.0-1.0)
  minimum_similarity: 0.7
  
  # 字符串预处理
  normalize_case: true
  remove_special_chars: true
  
  # 模糊匹配参数
  fuzzy_ratio_threshold: 80

# 推荐评分配置
scoring:
  # 评分权重
  download_count_weight: 0.3
  rating_weight: 0.4
  upvote_ratio_weight: 0.2
  recency_weight: 0.1
  
  # 最小评分要求
  minimum_rating: 0.5
  minimum_downloads: 10

# 难度分析配置
difficulty:
  # 难度分类阈值 (每秒方块数)
  categories:
    easy: 
      min: 0
      max: 4
      folder: "Easy (0-4 blocks/s)"
    
    medium:
      min: 4
      max: 7
      folder: "Medium (4-7 blocks/s)"
    
    hard:
      min: 7
      max: 999
      folder: "Hard (7+ blocks/s)"

# 文件处理配置
files:
  # 支持的音频格式
  supported_audio_formats: 
    - ".mp3"
    - ".flac"
    - ".ogg"
    - ".wav"
    - ".m4a"
    - ".aac"
  
  # 下载配置
  download_timeout: 300
  max_concurrent_downloads: 3
  
  # 文件组织
  organize_by_difficulty: true
  preserve_original_structure: false

# 网络配置
network:
  # 连接池大小
  connection_pool_size: 10
  
  # 超时配置
  connect_timeout: 10
  read_timeout: 30
  
  # 重试配置
  max_retries: 3
  retry_delay: 2.0
  backoff_factor: 2.0

# 性能配置
performance:
  # 并发处理
  max_concurrent_tasks: 5
  
  # 内存使用
  max_cache_size: 1000
  
  # 进度显示
  show_progress: true

# 跨平台路径使用说明:
# 
# Linux/macOS 系统:
#   音乐目录: /home/用户名/音乐/ 或 /Users/用户名/Music/
#   输出目录: /home/用户名/beatsaber_maps/ 或 /Users/用户名/BeatSaber/
#   命令示例: python main.py --music-dir "/home/用户名/音乐" --output-dir "/home/用户名/beatsaber_maps"
#
# Windows 系统:
#   音乐目录: "C:\Users\用户名\Music" 或 "D:\我的音乐"
#   输出目录: "C:\Users\用户名\Documents\BeatSaber Maps"
#   命令示例: python main.py --music-dir "C:\Users\用户名\Music" --output-dir "C:\Users\用户名\BeatSaber"
#   
# 注意: Windows用户可以使用 config/windows_settings.yaml 作为参考配置